### ISSUE TITLE
up，代码怎么没有了

### ISSUE THREAD

**Issue by simple123456T** [NephrenCake/GestureInteraction#1]
up，代码怎么没有了，
求代码

**Comment by NephrenCake** [comment]
代码都放在这里很久没动了，不清楚你说什么东西没有了

**Comment by simple123456T** [comment]
就是下面图片中的代码
![image](https://user-images.githubusercontent.com/104408880/171168784-a15ce839-6f66-4a4e-9062-bda882c8cfe8.png)

**Comment by simple123456T** [comment]
> 

sorry，没看到
