### ISSUE TITLE
如何调用摄像头进行运行

### ISSUE THREAD

**Issue by simple123456T** [NephrenCake/GestureInteraction#2]
您好，请问怎么才能调用摄像头进行实时检测

**Comment by NephrenCake** [comment]
https://github.com/NephrenCake/GestureInteraction/blob/82c53a114f02cdca0b2d1830e0c9bb86cf873061/Abyss/inference.py#L195
source值改为0

**Comment by simple123456T** [comment]
调用摄像头报错
![image](https://user-images.githubusercontent.com/104408880/171309364-6199672a-f143-453d-af3b-5e5794d76963.png)

**Comment by NephrenCake** [comment]
一般我不用摄像头，你可以换视频源，或者就按照他说的加一个.cpu()自己改一下
